export const prestoMarketFactoryAbi = [
  {
    type: 'function',
    name: 'marketCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'markets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'resolver', type: 'address' },
      { name: 'closeTime', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
      { name: 'marketKind', type: 'uint8' },
    ],
    outputs: [{ name: 'market', type: 'address' }],
  },
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'market', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'resolver', type: 'address', indexed: false },
      { name: 'marketKind', type: 'uint8', indexed: false },
      { name: 'closeTime', type: 'uint256', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
    ],
  },
] as const;

export const prestoMultiOutcomeMarketFactoryAbi = [
  {
    type: 'function',
    name: 'marketCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'markets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'resolver', type: 'address' },
      { name: 'closeTime', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
      { name: 'marketKind', type: 'uint8' },
      { name: 'outcomeCount', type: 'uint8' },
    ],
    outputs: [{ name: 'market', type: 'address' }],
  },
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'market', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'resolver', type: 'address', indexed: true },
      { name: 'marketKind', type: 'uint8', indexed: false },
      { name: 'closeTime', type: 'uint256', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
      { name: 'outcomeCount', type: 'uint8', indexed: false },
    ],
  },
] as const;

export const prestoMarketAbi = [
  {
    type: 'function',
    name: 'creator',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'resolver',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'collateral',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'closeTime',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'protocolFeeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'marketKind',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'outcomeCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'metadataURI',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'state',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'winningOutcome',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'totalCollateral',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'resolvedCollateral',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'resolutionURI',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'proposedOutcome',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'proposalProposer',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'proposalTime',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'proposalURI',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    type: 'function',
    name: 'proposalDisputed',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'proposalChallengeEndsAt',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalShares',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint8' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'sharesOf',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'uint8' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimed',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'previewClaim',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      { name: 'payout', type: 'uint256' },
      { name: 'fee', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'previewRefund',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'previewBuy',
    stateMutability: 'view',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'impliedProbabilityBps', type: 'uint256' },
      { name: 'estimatedPayout', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'buy',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'resolutionURI_', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'proposeResolution',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'resolutionURI_', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'disputeResolution',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'reason', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleProposedResolution',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancel',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'timeoutCancel',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'refund',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'event',
    name: 'SharesBought',
    inputs: [
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Claimed',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Refunded',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MarketResolved',
    inputs: [
      { name: 'winningOutcome', type: 'uint8', indexed: true },
      { name: 'resolutionURI', type: 'string', indexed: false },
      { name: 'resolvedCollateral', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionProposed',
    inputs: [
      { name: 'proposer', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: true },
      { name: 'resolutionURI', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionDisputed',
    inputs: [
      { name: 'disputer', type: 'address', indexed: true },
      { name: 'reason', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MarketCanceled',
    inputs: [],
  },
] as const;

export const prestoLmsrMarketFactoryAbi = [
  {
    type: 'function',
    name: 'marketCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'markets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createMarket',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'resolver', type: 'address' },
      { name: 'closeTime', type: 'uint64' },
      { name: 'metadataURI', type: 'string' },
      { name: 'marketKind', type: 'uint8' },
      { name: 'outcomeCount', type: 'uint8' },
      { name: 'seed6', type: 'uint256' },
    ],
    outputs: [{ name: 'market', type: 'address' }],
  },
  {
    type: 'event',
    name: 'MarketCreated',
    inputs: [
      { name: 'market', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'resolver', type: 'address', indexed: true },
      { name: 'marketKind', type: 'uint8', indexed: false },
      { name: 'closeTime', type: 'uint256', indexed: false },
      { name: 'metadataURI', type: 'string', indexed: false },
    ],
  },
] as const;

// LMSR (V3) market: live per-outcome pricing, buy/sell early exit, bonded optimistic resolution.
export const prestoLmsrMarketAbi = [
  { type: 'function', name: 'creator', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'resolver', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'collateral', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'closeTime', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint64' }] },
  { type: 'function', name: 'marketKind', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8' }] },
  { type: 'function', name: 'outcomeCount', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8' }] },
  { type: 'function', name: 'metadataURI', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'string' }] },
  { type: 'function', name: 'state', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8' }] },
  { type: 'function', name: 'winningOutcome', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8' }] },
  { type: 'function', name: 'feeBps', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint16' }] },
  { type: 'function', name: 'bond6', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { type: 'function', name: 'accruedFees6', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { type: 'function', name: 'seeded', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'bool' }] },
  { type: 'function', name: 'proposedOutcome', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8' }] },
  { type: 'function', name: 'proposer', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'disputer', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { type: 'function', name: 'proposalChallengeEndsAt', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint64' }] },
  {
    type: 'function',
    name: 'price',
    stateMutability: 'view',
    inputs: [{ name: 'outcome', type: 'uint8' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'buyCost',
    stateMutability: 'view',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'shares6', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'sellRefund',
    stateMutability: 'view',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'shares6', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalShares',
    stateMutability: 'view',
    inputs: [{ name: 'outcome', type: 'uint8' }],
    outputs: [{ name: '', type: 'int256' }],
  },
  {
    type: 'function',
    name: 'sharesOf',
    stateMutability: 'view',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'who', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  { type: 'function', name: 'seed', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    type: 'function',
    name: 'buy',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'shares6', type: 'uint256' },
      { name: 'maxCost6', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'sell',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'shares6', type: 'uint256' },
      { name: 'minRefund6', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'propose',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'outcome', type: 'uint8' },
      { name: 'evidenceURI', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'dispute',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'reason', type: 'string' }],
    outputs: [],
  },
  { type: 'function', name: 'settle', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    type: 'function',
    name: 'resolveDisputed',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'finalOutcome', type: 'uint8' },
      { name: 'evidenceURI', type: 'string' },
    ],
    outputs: [],
  },
  { type: 'function', name: 'claim', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    type: 'function',
    name: 'payWinners',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'winners', type: 'address[]' }],
    outputs: [],
  },
  { type: 'function', name: 'refund', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'cancel', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'timeoutCancel', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'withdrawFees', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  // Guardian-only pause controls + the paused view. Pausing freezes buy/sell (whenNotPaused) so an
  // early-decided market can be frozen until it resolves at close.
  { type: 'function', name: 'pause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'unpause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'paused', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'bool' }] },
  { type: 'function', name: 'guardian', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  {
    type: 'event',
    name: 'SharesBought',
    inputs: [
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: true },
      { name: 'shares6', type: 'uint256', indexed: false },
      { name: 'cost6', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SharesSold',
    inputs: [
      { name: 'seller', type: 'address', indexed: true },
      { name: 'outcome', type: 'uint8', indexed: true },
      { name: 'shares6', type: 'uint256', indexed: false },
      { name: 'refund6', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionProposed',
    inputs: [
      { name: 'outcome', type: 'uint8', indexed: true },
      { name: 'proposer', type: 'address', indexed: true },
      { name: 'evidenceURI', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ResolutionDisputed',
    inputs: [
      { name: 'disputer', type: 'address', indexed: true },
      { name: 'reason', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Resolved',
    inputs: [{ name: 'outcome', type: 'uint8', indexed: true }],
  },
  {
    type: 'event',
    name: 'WinnerPaid',
    inputs: [
      { name: 'winner', type: 'address', indexed: true },
      { name: 'amount6', type: 'uint256', indexed: false },
    ],
  },
  { type: 'event', name: 'MarketCanceled', inputs: [] },
  {
    type: 'event',
    name: 'Refunded',
    inputs: [
      { name: 'holder', type: 'address', indexed: true },
      { name: 'amount6', type: 'uint256', indexed: false },
    ],
  },
] as const;

export const erc20Abi = [
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const;
